version: '3'
services:
 docker-app:
    image: marcos/docker-compass-app
    ports:
      - "8080:8080"
    depends_on:
      - db
 db:
    image: postgres:10.4
    environment:
      - POSTGRES_DB=compasso
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
    - 5433:5432